name: Deploy to FTP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Upload via FTP
        run: |
          lftp -d -c "
          set ftp:ssl-allow no;
          open ftp://$FTP_USER:$FTP_PASS@$FTP_HOST;
          ls;
          mirror -R ./web /htdocs;
          "
